on:
  workflow_dispatch:
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: 安装node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: 安装项目依赖
        working-directory: ../vue-demo
        run: npm install
      - name: 打包
        working-directory: ../vue-demo
        run: npm run build
