on:
  workflow_dispatch:
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: 安装node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: 安装项目依赖
        working-directory: vue-demos
        run: npm install
      - name: 打包
        working-directory: vue-demos
        run: npm run build
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: vue-demos/mapotato
          target: /home/nginx/html/haha/test  # 替换为你的服务器目录
